### ISSUE TITLE
HGNC gene family IDs fail to resolve

### ISSUE THREAD

**Issue by cmungall** [pyobo/examples#2]
```yaml
[Term]
id: hgnc:5956
name: IHH
def: "Indian hedgehog signaling molecule" [pubmed:7590746, pubmed:14770182]
xref: ccds:CCDS33380
xref: ena:L38517
xref: ensembl:ENSG00000163501
xref: merops:C46.003
xref: ncbigene:3549
xref: omim:600726
xref: orphanet:122605
xref: refseq:NM_002181
xref: ucsc:uc002vjo.3
xref: vega:OTTHUMG00000154631
is_a: hgnc.genefamily:1373 ! Hedgehog signaling molecule family
is_a: hgnc.genefamily:1691 ! MicroRNA protein coding host genes
relationship: ro:0002205 uniprot:Q14623
relationship: ro:HOM0000017 rgd:620021
relationship: ro:HOM0000017 mgi:96533
relationship: ro:0002162 ncbitaxon:9606
property_value: locus_group "protein-coding gene" xsd:string
property_value: locus_type "gene with protein product" xsd:string
property_value: location "2q35" xsd:string
synonym: "BDA1" EXACT alias_symbol []
synonym: "HHG2" EXACT alias_symbol []
synonym: "Indian hedgehog (Drosophila) homolog" EXACT previous_name []
```

https://bioregistry.io/hgnc.genefamily:1373 -->
https://registry.identifiers.org/deprecation/resources/MIR:00100671/1373

with a 404 "go home" message :-(

![image](https://user-images.githubusercontent.com/50745/133313220-b88428bf-2471-45bd-823e-0286990049b2.png)
