### ISSUE TITLE
OBO CURIEs (e.g. RO) should be uppercase 

### ISSUE THREAD

**Issue by cmungall** [pyobo/examples#3]
```yaml
[Term]
id: hgnc:5956
name: IHH
def: "Indian hedgehog signaling molecule" [pubmed:7590746, pubmed:14770182]
xref: ccds:CCDS33380
xref: ena:L38517
xref: ensembl:ENSG00000163501
xref: merops:C46.003
xref: ncbigene:3549
xref: omim:600726
xref: orphanet:122605
xref: refseq:NM_002181
xref: ucsc:uc002vjo.3
xref: vega:OTTHUMG00000154631
is_a: hgnc.genefamily:1373 ! Hedgehog signaling molecule family
is_a: hgnc.genefamily:1691 ! MicroRNA protein coding host genes
relationship: ro:0002205 uniprot:Q14623
relationship: ro:HOM0000017 rgd:620021
relationship: ro:HOM0000017 mgi:96533
relationship: ro:0002162 ncbitaxon:9606
property_value: locus_group "protein-coding gene" xsd:string
property_value: locus_type "gene with protein product" xsd:string
property_value: location "2q35" xsd:string
synonym: "BDA1" EXACT alias_symbol []
synonym: "HHG2" EXACT alias_symbol []
synonym: "Indian hedgehog (Drosophila) homolog" EXACT previous_name []
```

Neither obo nor owl will treat these as being the same IDs as RO:0002205 etc

But awesome to see RO uses this way!
